### ISSUE TITLE
produce training rect

### ISSUE THREAD

**Issue by gulzainali98** [NeuralCollapseApplications/FSCIL#6]
I am not sure what produce_training_rect function is supposed to do and why is it used for few shot sessions only?

**Comment by gulzainali98** [comment]
It seems it is weighting weights of classifier up and down based on the number of samples in a mini batch.

**Comment by iboing** [comment]
yes, in incremental sessions, train samples of novel classes and features of old classes from the memory are imbalanced, so we use this re-weight strategy. Base session has balanced training data.
