### ISSUE TITLE
I cannot reproduce the training results on the CIFAR100 dataset, especially in the last few incremental sessions.

### ISSUE THREAD

**Issue by lzwqjh** [NeuralCollapseApplications/FSCIL#8]
Hi, we use the docker command provided to run the code. On the cifar100 dataset, starting from the fifth session, the accuracy dropped to very low. Below is my log file:
[20231219_095703.log](https://github.com/NeuralCollapseApplications/FSCIL/files/13710818/20231219_095703.log)
Any help would be greatly appreciated

**Comment by HarborYuan** [comment]
Hi @lzwqjh ,

Thanks for your interest.

I found that you use 4 GPUs for training. Did you adjust the batch size based on the number of GPUs? Please take a look at #3 for details.
